hawkfish/olapscript

.gitignore
olap-script.js
package-lock.json
package.json
test/test_expr.js

Nodify the project and add Expr tests.

Issue #5: Mocha Tests

---

githubapi.js

Convert some hard-coded constants to function parameters.

Issue #4: Apps Script Connector

---

src/table.js
test/fixtures/alice1.json
test/fixtures/alice2.json
test/test_union.js

Issue #10: Implement UNION ALL

---

src/table.js

Implement Table.tables and Table.columns to enumerate schema metadata.
Add limit option to fromTable to improve schema detection performance.

Issue #11: Schema Enumeration

---

src/table.js
test/mocks/mock-sheet.js
test/test_from_sheet.js

Generate replacement columns names with trailing numbers when a sheet has duplicate column names.

Issue #7: Deduplicate Column Name

---

.editorconfig
src/table.js
test/test_equijoin.js

* Test to make sure it works!
* Change keys to be expression trees
* Add outer join support.

Issue #5: Outer Hash Joins

---

src/expr.js
test/test_strings.js
test/test_time.js

This included trimming and today/now.

Issue #21: Create Function Library

---

src/expr.js
test/test_expr.js
test/test_logical.js

Add AND OR NOT to the Expr library.

Issue #24: Add Logical Functions

---

src/expr.js
test/test_conditionals.js

eq, ne, le, lt, ge, gt, isdistinct, isnotdistinct, isnull, isnotnull

Issue #25: Implement Conditional Functions

---

src/expr.js
test/test_cast.js

Needs to special case Date and Array to get reasonable behaviour.

Issue #27: Add Cast Function

---

.gitignore
src/expr.js
src/table.js
test/test_expr.js
test/test_time.js

Implement CASE as a new expression type so it can short circuit.

Issue #29: CASE Expressions

---

src/expr.js
src/table.js
test/test_expr.js
test/test_groupby.js

Issue #31: Test GROUP BY

---

src/aggr.js
src/table.js
test/test_aggr.js
test/test_groupby.js

Change the way aggregates are implemented to be Objects instead of classes.

Issue #33: Aggregate Initialize

---

src/expr.js
test/test_strings.js

Equivalent to String.includes but with null testing.

Issue #35: Implement CONTAINS

---

src/aggr.js
test/test_aggr.js

Implement a bunch of useful aggregates.

Issue #34: MIN, MAX Etc.

---

src/table.js
test/test_examples.js

Add tests and fix the example code to work.

Issue #39: Test Example Code

---

src/table.js
test/test_from_sheet.js

* Allow the caller to specify a different top left than A1.
* Multi-row headers
* Headers detached from the data
* Headers missing (F1...)
* User specified headers

FromSheet Layout

---

src/table.js
test/test_equijoin.js

Accept left and right as aliases for probe and build (resp.).

Issue #46: Left Right Aliases

---

src/table.js
test/test_from_sheet.js

Add a dataBounds option to fromSheet that takes an
Array of column indexes and finds the covering range of
non-empty values to update the top and limit.

Issue #45: FromSheet Data Bounds

---

src/expr.js
test/test_expr.js

Issue #49: Did You Mean

---

olapscript.gs
tools/amalgamate.sh

Script and output.  Should get triggered somehow.

Issue #44: Create Amalgamation Version

---

olapscript.gs
src/expr.js
test/test_expr.js

Move the fancy formatting to a toString method and just return "case"for CaseExpr

Issue #49: CaseExpr alias

---

src/table.js
test/test_rows.js

Issue #69: Add toRows

---

src/table.js
test/mocks/mock-sheet.js

The last two arguments to getRange are sizes, not indicies.

Issue #60: Sheet GetRange Usage

---

src/aggr.js
src/column.js
src/expr.js
src/table.js

Add comments to indicate that a block is related to node import/export.

Issue #64: Comment Node Connections

---

src/expr.js
test/test_conditionals.js

The SQL `x BETWEEN a AND b` is equivalent to `(a <= x AND x <= b)`
The function is `between(x, a, b)`

Issue #66: Implement BETWEEN Function

---

test/test_unnest.js

Issue #73: Test Unnest

---

src/table.js
test/test_from_sheet.js

Switch to using A..ZZ column names instead of Fn.
Also, use them for missing column names.

Issue #84: Missing Column Names

---

src/table.js
test/mocks/mock-sheet.js
test/test_from_sheet.js

Apps Script throws an Error when you ask for zero rows. Since that is not an unreasonable thing to do,
check for it and produce empty data columns.

Issue #89: From Zero Rows

---

src/table.js
test/mocks/mock-sheet.js
test/test_from_sheet.js

Handle completely empty sheets.

Issue #91: From Empty Sheet

---

docs/as_examples.md
docs/column.md
docs/expressions.md
docs/home.md
docs/scalars.md
docs/table.md

Add the current versions of the wiki docs to the code tree.

Issue #94: Check In Wiki

---

olapscript.gs
src/table.js
test/test_equijoin.js

Use the actual selection vector value, not the index into the SV...

Issue #97: EquiJoin Selections

---

olapscript.gs
package.json
src/expr.js
src/table.js
src/timestamp.js
test/test_conditionals.js
test/test_examples.js
test/test_from_sheet.js
test/test_select.js
test/test_time.js

* Create the SQLDate class.
* Fix date comparisons.

Date Issues

---

olapscript.gs
src/table.js
test/test_from_sheet.js

Strip trailing spaces from column names.

Issue #48: Strip Trailing Spaces

---

docs/table.md
olapscript.gs
src/table.js

This is now off by default but can be enabled using the clear flag in the new options argument.

Issue #86: ToSheet Clearing

---

docs/table.md
olapscript.gs
src/table.js
test/mocks/mock-sheet.js
test/test_to_sheet.js

Allow overriding the top left as an insertion point.

Issue #79: toSheet Output Location
